torchrun --nnodes=1 --nproc_per_node=4 --master_port=25001 \
    llava/train/train.py \
    --model_name_or_path /data/bingchen_zhao/llama-2/models_hf/7B/ \
    --version v0 \
    --data_path /data/bingchen_zhao/data/LLaVA-Instruct-150K/llava_instruct_150k.json \
    --image_folder /data/bingchen_zhao/data/coco/train2017/ \
    --vision_tower openai/clip-vit-large-patch14 \
    --pretrain_mm_mlp_adapter /data/bingchen_zhao/weights/llava/llava-llama-2-7b-pretrain/mm_projector.bin \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end True \
    --bf16 True \
    --output_dir /data/bingchen_zhao/weights/llava/llava-llama-2-7b-finetune/ \
    --num_train_epochs 3 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 2 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 5000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --fsdp "full_shard auto_wrap" \
    --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb
